## Álgebra linear

A álgebra linear é um ramo da matemática que estuda os coneceitos e a propriedades de estruturas abstratas chamadas espaços vetoriais, matrizes, transformações lineares, sistemas de equações lineares e determinantes. A álgebra linear tem aplicações em diversas áreas do conhecimento, como física, computação, engenharia, economia e ciência de dados. A álgebra linear também fornece ferramentas para o estudo de geometria analítica, análise funcional, equação diferenciais e otimização.

<img src="https://github.com/1998-sys/santander_coders2024/raw/79da18a7953620b131d098537dd825c66346f71e/LimeWire%20AI%20Studio%20Asset.jpg" alt="Imagem">

In [11]:
matriz_a = [[1,2,3],[4,5,6]]

In [12]:
matriz_a

[[1, 2, 3], [4, 5, 6]]

In [13]:
matriz_a[0] # Acessando a primeira linha 

[1, 2, 3]

In [14]:
matriz_a[1] # Acessando a segunda linha 


[4, 5, 6]

In [15]:
matriz_a[0][1] #elemento da primeira linha e segunda coluna

2

Usar listas aninhadas como matriz funciona para tarefas computacionais simples, no entanto, exite uma maneira melhor de trabalhar com matrizes em python usando o pacote Numpy

### Numpy Array: Numpy
Numpy é um pacote para computação científica que fornece uma ampla gama de  funções e métodos para trabalhar com matrizes multidimensionais

In [18]:
import numpy as np 

matriz_b = np.array([[1,2,3], [4,5,6], [7,8,9]])

matriz_b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
# Acessando a matriz 
matriz_b[0][2] # Acessando primeira linha 3° coluna

3

Algumas operações que podemos realizar em matrizes usando o Numpy 

- Transposiçaõ de matriz

A transposição de uma matriz é uma operação que troca as linhas e colunas da matriz. Por exemplo, se tivermos uma matriz A com a dimensão m x n, a transposta de A é uma matriz B com dimensão nxm, onde o elemento na linha i e colna j de B é o elemento na linha j e coluna i de A

In [21]:
matriz_b.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

- Adição de matrizes

A adição e subtração de matrizes são realizadas elemento por elemento. Para que duas matrizes possam ser adicionadas ou subtraídas, elas devem ter a mesma dimensão. Por exemplo, se tivermos duas matrizes A e B, ambas com dimensão mxn, a soma de A e B é uma matriz C, onde cada elemento de C é a soma dos elementos correspondentes de A e B

In [23]:
matriz_1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
matriz_2 = np.array([[9,8,7],[6,5,4],[3,2,1]])

soma = matriz_1 + matriz_2
print(soma)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


- Subtração de Matrizes

In [25]:
subtração = matriz_1 - matriz_2
subtração

array([[-8, -6, -4],
       [-2,  0,  2],
       [ 4,  6,  8]])

- Multiplicação de Matrizes

A multiplicação de matrizes é um pouco mais complexa. A multiplicação de duas matrizes A e B é definida apenas se o número de colunas de A for igual ao número de linhas de B. O resultado da multiplicação é uma matriz C, onde o elemento na linha i e coluna j é o produto escalar da linha i de A e da coluna j de B

O número de colunas da primeira matriz deve ser igual ao número de linhas da segunda matriz 


In [33]:
matriz3 = np.array([[1,2], [3,4], [5,6]])
matriz4 = np.array([[7], [8]])

print(matriz3)
print(matriz4)

matrizmult = np.dot(matriz3, matriz4) #Comando para realizar multiplicação de matrizes
matrizmult

[[1 2]
 [3 4]
 [5 6]]
[[7]
 [8]]


array([[23],
       [53],
       [83]])

- Divisão de matrizes

Tecnicamente, a divisão de matrizes não existe. Em vez disso, é necessário multiplicar uma matriz pelo inverso da outra. Por exemplo, se tibermos duas matrizes A e B, a divisão de A por B seria escrita como A*B^-1. Para calcular a divisão de matrizes, a matriz b deve ser quadrada e seu determinante deve ser diferente de zero. Caso contráriom a divisão não é possível.
