## Álgebra linear

A álgebra linear é um ramo da matemática que estuda os coneceitos e a propriedades de estruturas abstratas chamadas espaços vetoriais, matrizes, transformações lineares, sistemas de equações lineares e determinantes. A álgebra linear tem aplicações em diversas áreas do conhecimento, como física, computação, engenharia, economia e ciência de dados. A álgebra linear também fornece ferramentas para o estudo de geometria analítica, análise funcional, equação diferenciais e otimização.

<img src="https://github.com/1998-sys/santander_coders2024/raw/79da18a7953620b131d098537dd825c66346f71e/LimeWire%20AI%20Studio%20Asset.jpg" alt="Imagem">

In [1]:
matriz_a = [[1,2,3],[4,5,6]]

In [2]:
matriz_a

[[1, 2, 3], [4, 5, 6]]

In [3]:
matriz_a[0] # Acessando a primeira linha 

[1, 2, 3]

In [4]:
matriz_a[1] # Acessando a segunda linha 


[4, 5, 6]

In [5]:
matriz_a[0][1] #elemento da primeira linha e segunda coluna

2

Usar listas aninhadas como matriz funciona para tarefas computacionais simples, no entanto, exite uma maneira melhor de trabalhar com matrizes em python usando o pacote Numpy

### Numpy Array: Numpy
Numpy é um pacote para computação científica que fornece uma ampla gama de  funções e métodos para trabalhar com matrizes multidimensionais

In [6]:
import numpy as np 

matriz_b = np.array([[1,2,3], [4,5,6], [7,8,9]])

matriz_b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
# Acessando a matriz 
matriz_b[0][2] # Acessando primeira linha 3° coluna

3

Algumas operações que podemos realizar em matrizes usando o Numpy 

- Transposiçaõ de matriz

A transposição de uma matriz é uma operação que troca as linhas e colunas da matriz. Por exemplo, se tivermos uma matriz A com a dimensão m x n, a transposta de A é uma matriz B com dimensão nxm, onde o elemento na linha i e colna j de B é o elemento na linha j e coluna i de A

In [8]:
matriz_b.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

- Adição de matrizes

A adição e subtração de matrizes são realizadas elemento por elemento. Para que duas matrizes possam ser adicionadas ou subtraídas, elas devem ter a mesma dimensão. Por exemplo, se tivermos duas matrizes A e B, ambas com dimensão mxn, a soma de A e B é uma matriz C, onde cada elemento de C é a soma dos elementos correspondentes de A e B

In [9]:
matriz_1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
matriz_2 = np.array([[9,8,7],[6,5,4],[3,2,1]])

soma = matriz_1 + matriz_2
print(soma)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


- Subtração de Matrizes

In [10]:
subtração = matriz_1 - matriz_2
subtração

array([[-8, -6, -4],
       [-2,  0,  2],
       [ 4,  6,  8]])

- Multiplicação de Matrizes

A multiplicação de matrizes é um pouco mais complexa. A multiplicação de duas matrizes A e B é definida apenas se o número de colunas de A for igual ao número de linhas de B. O resultado da multiplicação é uma matriz C, onde o elemento na linha i e coluna j é o produto escalar da linha i de A e da coluna j de B

O número de colunas da primeira matriz deve ser igual ao número de linhas da segunda matriz 


In [11]:
matriz3 = np.array([[1,2], [3,4], [5,6]])
matriz4 = np.array([[7], [8]])

print(matriz3)
print(matriz4)

matrizmult = np.dot(matriz3, matriz4) #Comando para realizar multiplicação de matrizes
matrizmult

[[1 2]
 [3 4]
 [5 6]]
[[7]
 [8]]


array([[23],
       [53],
       [83]])

- Divisão de matrizes

Tecnicamente, a divisão de matrizes não existe. Em vez disso, é necessário multiplicar uma matriz pelo inverso da outra. Por exemplo, se tibermos duas matrizes A e B, a divisão de A por B seria escrita como A*B^-1. Para calcular a divisão de matrizes, a matriz b deve ser quadrada e seu determinante deve ser diferente de zero. Caso contráriom a divisão não é possível.


## Matriz Transposta

A matriz trasposta é uma matriz que se obtém ao trocar as linhas pelas colunas de uma matriz. A representação matemática da matriz transposta de uma matriz A é:
$$ A^\top $$


In [15]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [18]:
# Matriz transposta
at = np.transpose(a)
print(at)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [20]:
# Outra forma de obter a matriz transposta
a.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

## Matriz Inversa
A matriz inversa é uma matriz que é obtida a partir de uma matriz quadrada A, tal que o produto entre A e sua inversa resulta na matriz identidade. A inversa de uma matriz A é denotada por: $$ A^{-1} $$
Para calcular a matriz inversa de uma matriz A, é necessário que o determinte de A seja diferente de zero.


A matriz inversa tem algumas propriedades interessantes, como:

- A inversa de uma matriz é igual a matriz original: 
$$ (A^{-1})^{-1} = A $$

- A inversa da matriz identidade é igual a matriz identidade:
$$ I^{-1} = I $$

- A inversa da soma de duas matrizes é igual à soma das inversas de cada matriz:

$$ (A+B^{-1}) = A^{-1} + B^{-1}$$

- A multiplicação da matriz original pela matriz inversa gera a matriz identidade
$$ A * (A^{-1}) = I$$

In [30]:
a = np.array([[1,1,-3],[2,1,3],[2,0,-1]]) # Matriz,
a


array([[ 1,  1, -3],
       [ 2,  1,  3],
       [ 2,  0, -1]])

In [33]:
# Para a matriz A ter matriz inversa:
# Matriz original tem que ser quadrada: 3x3
# Determinante tem que ser diferente de zero

# Cálculo do determinante
np.linalg.det(a) # det(A) = 13, ou seja, diferente de zero ->> matriz A tem inversa

13.0

In [36]:
# Calculando a inversa da Matriz A
a_inve = np.linalg.inv(a)
print(a_inve)


[[-0.07692308  0.07692308  0.46153846]
 [ 0.61538462  0.38461538 -0.69230769]
 [-0.15384615  0.15384615 -0.07692308]]


In [39]:
# Identidade

id = np.dot(a, a_inve) # A multiplicação resulta a matriz identidade
print(id)

[[ 1.00000000e+00 -5.55111512e-17  5.55111512e-17]
 [ 0.00000000e+00  1.00000000e+00  5.55111512e-17]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]
