## Álgebra linear

A álgebra linear é um ramo da matemática que estuda os coneceitos e a propriedades de estruturas abstratas chamadas espaços vetoriais, matrizes, transformações lineares, sistemas de equações lineares e determinantes. A álgebra linear tem aplicações em diversas áreas do conhecimento, como física, computação, engenharia, economia e ciência de dados. A álgebra linear também fornece ferramentas para o estudo de geometria analítica, análise funcional, equação diferenciais e otimização.

<img src="https://github.com/1998-sys/santander_coders2024/raw/79da18a7953620b131d098537dd825c66346f71e/LimeWire%20AI%20Studio%20Asset.jpg" alt="Imagem">

In [1]:
matriz_a = [[1,2,3],[4,5,6]]

In [2]:
matriz_a

[[1, 2, 3], [4, 5, 6]]

In [3]:
matriz_a[0] # Acessando a primeira linha 

[1, 2, 3]

In [4]:
matriz_a[1] # Acessando a segunda linha 


[4, 5, 6]

In [5]:
matriz_a[0][1] #elemento da primeira linha e segunda coluna

2

Usar listas aninhadas como matriz funciona para tarefas computacionais simples, no entanto, exite uma maneira melhor de trabalhar com matrizes em python usando o pacote Numpy

### Numpy Array: Numpy
Numpy é um pacote para computação científica que fornece uma ampla gama de  funções e métodos para trabalhar com matrizes multidimensionais

In [6]:
import numpy as np 

matriz_b = np.array([[1,2,3], [4,5,6], [7,8,9]])

matriz_b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
# Acessando a matriz 
matriz_b[0][2] # Acessando primeira linha 3° coluna

3

Algumas operações que podemos realizar em matrizes usando o Numpy 

- Transposiçaõ de matriz

A transposição de uma matriz é uma operação que troca as linhas e colunas da matriz. Por exemplo, se tivermos uma matriz A com a dimensão m x n, a transposta de A é uma matriz B com dimensão nxm, onde o elemento na linha i e colna j de B é o elemento na linha j e coluna i de A

In [8]:
matriz_b.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

- Adição de matrizes

A adição e subtração de matrizes são realizadas elemento por elemento. Para que duas matrizes possam ser adicionadas ou subtraídas, elas devem ter a mesma dimensão. Por exemplo, se tivermos duas matrizes A e B, ambas com dimensão mxn, a soma de A e B é uma matriz C, onde cada elemento de C é a soma dos elementos correspondentes de A e B

In [9]:
matriz_1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
matriz_2 = np.array([[9,8,7],[6,5,4],[3,2,1]])

soma = matriz_1 + matriz_2
print(soma)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


- Subtração de Matrizes

In [10]:
subtração = matriz_1 - matriz_2
subtração

array([[-8, -6, -4],
       [-2,  0,  2],
       [ 4,  6,  8]])

- Multiplicação de Matrizes

A multiplicação de matrizes é um pouco mais complexa. A multiplicação de duas matrizes A e B é definida apenas se o número de colunas de A for igual ao número de linhas de B. O resultado da multiplicação é uma matriz C, onde o elemento na linha i e coluna j é o produto escalar da linha i de A e da coluna j de B

O número de colunas da primeira matriz deve ser igual ao número de linhas da segunda matriz 


In [11]:
matriz3 = np.array([[1,2], [3,4], [5,6]])
matriz4 = np.array([[7], [8]])

print(matriz3)
print(matriz4)

matrizmult = np.dot(matriz3, matriz4) #Comando para realizar multiplicação de matrizes
matrizmult

[[1 2]
 [3 4]
 [5 6]]
[[7]
 [8]]


array([[23],
       [53],
       [83]])

- Divisão de matrizes

Tecnicamente, a divisão de matrizes não existe. Em vez disso, é necessário multiplicar uma matriz pelo inverso da outra. Por exemplo, se tibermos duas matrizes A e B, a divisão de A por B seria escrita como A*B^-1. Para calcular a divisão de matrizes, a matriz b deve ser quadrada e seu determinante deve ser diferente de zero. Caso contráriom a divisão não é possível.


## Matriz Transposta

A matriz trasposta é uma matriz que se obtém ao trocar as linhas pelas colunas de uma matriz. A representação matemática da matriz transposta de uma matriz A é:
$$ A^\top $$


In [15]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [18]:
# Matriz transposta
at = np.transpose(a)
print(at)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [20]:
# Outra forma de obter a matriz transposta
a.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

## Matriz Inversa
A matriz inversa é uma matriz que é obtida a partir de uma matriz quadrada A, tal que o produto entre A e sua inversa resulta na matriz identidade. A inversa de uma matriz A é denotada por: $$ A^{-1} $$
Para calcular a matriz inversa de uma matriz A, é necessário que o determinte de A seja diferente de zero.


A matriz inversa tem algumas propriedades interessantes, como:

- A inversa de uma matriz é igual a matriz original: 
$$ (A^{-1})^{-1} = A $$

- A inversa da matriz identidade é igual a matriz identidade:
$$ I^{-1} = I $$

- A inversa da soma de duas matrizes é igual à soma das inversas de cada matriz:

$$ (A+B^{-1}) = A^{-1} + B^{-1}$$

- A multiplicação da matriz original pela matriz inversa gera a matriz identidade
$$ A * (A^{-1}) = I$$

In [30]:
a = np.array([[1,1,-3],[2,1,3],[2,0,-1]]) # Matriz,
a


array([[ 1,  1, -3],
       [ 2,  1,  3],
       [ 2,  0, -1]])

In [33]:
# Para a matriz A ter matriz inversa:
# Matriz original tem que ser quadrada: 3x3
# Determinante tem que ser diferente de zero

# Cálculo do determinante
np.linalg.det(a) # det(A) = 13, ou seja, diferente de zero ->> matriz A tem inversa

13.0

In [36]:
# Calculando a inversa da Matriz A
a_inve = np.linalg.inv(a)
print(a_inve)


[[-0.07692308  0.07692308  0.46153846]
 [ 0.61538462  0.38461538 -0.69230769]
 [-0.15384615  0.15384615 -0.07692308]]


In [39]:
# Identidade

id = np.dot(a, a_inve) # A multiplicação resulta a matriz identidade
print(id)

[[ 1.00000000e+00 -5.55111512e-17  5.55111512e-17]
 [ 0.00000000e+00  1.00000000e+00  5.55111512e-17]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]


## Matriz Identidade

A matriz identidade é uma matriz quadrada em que os elementos da diagonal principal são iguais a 1 e os demais elementos são iguais a 0. A matriz identidade é considerada o elemento neutro da multiplicação de matrizes, ou seja, se multiplicarmos uma matriz M pela identidade, encontramos como resultado a própria matriz M. A representação matemática da matriz identidade de ordem n é:
$$ \mathbf{I}_{n} $$

A matriz identidade possui algumas propriedades interesssantes, como:

- O produto entra uma matriz quadrada A e sua matriz identidade correspondente é igual à própria matriz A:
$$ A * {I}_{n} = I_{n} * A = A $$

- O produto entre uma matriz quadrada A e sua matriz inversa correspondente é igual a matriz identidade
$$ A * A^{-1} = A^{-1} * A = I_{n}$$

- A matriz identidade é única para cada ordem n.

- Matriz identidade de ordem 2:
$$\mathbf{I}_{2} = \begin{pmatrix}
1 & 0 \\
0 & 1  
\end{pmatrix}$$

- Matriz identidade de odem 3:
$$\mathbf{I}_{3} = \begin{pmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1
\end{pmatrix}$$

In [43]:
# Criando a matriz identidade
i = np.identity(3)
i

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [44]:
# Criando a matriz identidade
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

## Determinantes

A motivação da criação dos determinantes em matemática foi para resolver problemas relacionados aos sistemas de equações lineares, ou simplesmente, sistemas lineares. Posteriormente foram definidos matematicamente para o estudo teórico dos mesmos.

O determinante de uma matriz quadrada é o número que pode ser obtido por meio de diversos métodos, dependendo da ordem da matriz, Para matrizes de ordem 1, o determinante é simplesmente o únido elemento da matriz. Para matrizes de ordem 2, o determinante é a diferença entre o produto dos elementos da diagonal principal e o produto dos elementos da diagonal secundária. Para matrizes de ordem 3 ou superior, existem diversas técnicas para calcular o determinante, como a regra de Sarrus o método de Laplace, entre outros.

O determinante de uma matriz quadrada A é um número real que pode obter vários significados dependendo do contexto. Seu cálculo passa por processos específicos. O determinante de uma matriz possui várias aplicações atualmente. Utilizamos o determinante para verificar se três pontos estão alinhados no plano cartesiano, para calcular áreas de triângulos, para resolução de sistemas lineares, entre outras aplicações na matemática. O estudo de determinantes não se limita à matemática, há algumas aplicações na física, como estudo de campos elétricos. Calculamos determinantes somente de matrizes quadradas, ou seja, matrizes em que a quantidade de colunas e a quantidade de linhas são iguais. Para calcular o determinante de uma matriz, precisamos analisar a ordem dela, ou seja, se ela é 1x1, 2x2, 3x3 e assim sucessivament, quanto maior sua ordem, mais difícil será encontrar o determinante. No entanto, há métodos importantes para realizar-se o exercício, como a regra de Sarrus, utilizada para calcular-se determinantes de matrizes 3x3.

Aqui estão alguns exemplos de determinantes:

- Determinante de uma matriz 1x1:
$$ a_{1} $$

In [47]:
matriz = np.array([[1,2,-3],[2,1,3],[2,0,-1]])

In [49]:
matriz

array([[ 1,  2, -3],
       [ 2,  1,  3],
       [ 2,  0, -1]])

In [51]:
det = np.linalg.det(matriz)
det

20.99999999999999

In [55]:
# Gerando uma matriz aleatória 
A = np.random.randint(0,10, size=(4,4))
A


array([[5, 3, 8, 8],
       [8, 9, 4, 3],
       [8, 6, 5, 4],
       [5, 7, 4, 6]])

In [57]:
detA = np.linalg.det(A)
detA

-261.99999999999994

In [60]:
# Não se calcula o determinante de uma matriz que não é quadrada
# (ou seja, que tem o número de linhas diferentes de colunas)
B = np.random.randint(0,10, size=(3,4))
detB = np.linalg.det(B)

LinAlgError: Last 2 dimensions of the array must be square

## Sistemas Lineares
Sistemas lineares são conjuntos de equações lineares qye envolvem várias variáveis, juntamente com a tarefa de encontra valores para essas variáveis que satisfaçam todas as equações simultaneamente. Eles podem ser resovidos por meio de diferentes métodos, como método da adição, igualdade e substituição para sistemas que possuem duas equações e duas incógnitas, é a regra de Crammer e o escalonamento, que resolvem sistemas lineares de duas equações, mas que são mais convenientes para sistemas com mais equações. Um sistema linear é um conjunto de duas ou mais equações como uma ou mais incógnitas.

Por exemplo, um sistema linear com duas equações e duas incógnitas pode ser representado da seguinte forma:

\begin{align}
a_{11}x + a_{12}y &= b_1 \\
a_{21}x + a_{22}y &= b_2
\end{align}

Onde a11, a12, a21 e a22 são os coeficientes das variáveis x1 e x2 e b1 e b2 são os termos independentes. O objetivo é encontrar valores para x1 e x2 que satisfaçam as equeações simultaneamente

Um sistema linear o m equações pode ser representado da seguinte forma:


\begin{align}
a_{11}x_1 + a_{12}x_2 + \cdots + a_{1n}x_n &= b_1 \\
a_{21}x_1 + a_{22}x_2 + \cdots + a_{2n}x_n &= b_2 \\
&\vdots \\
a_{n1}x_1 + a_{n2}x_2 + \cdots + a_{nn}x_n &= b_n
\end{align}

Onde aij são os coeficientes das variáveis xi, b, são os termos independentes e xi são as incógnitas. O objetivo é encontrar valores para x1, x2, ....., xn que satisfaçam todas as equações simultaneamente.

A forma matricial de um sistema linear é uma representação matemática que utiliza matrizes para simplificar a resolução de sistemas de equações lineares. Para transformar um sistema linear em sua forma matricial, basta escrever os coeficientes das variáveis em uma matriz e os termos independentes em outra matriz. Por exemplo, o sistema linear: 

\begin{align}
2_{x} + 3_{y} &= 7 \\
4_{x} + 5_{y} &= -3
\end{align}

Pode ser escrito na forma matricial como:

$$
\begin{pmatrix}
2 & 3 \\
4 & 5
\end{pmatrix}
\begin{pmatrix}
x \\
y
\end{pmatrix}
=
\begin{pmatrix}
7 \\
-3
\end{pmatrix}
$$

Onde a matriz dos coeficientes é chamada de matriz dos coeficientes, a matriz das variáveis é chamada de matriz das variáveis e matriz dos termos independentes é chamada de matriz dos termos independentes. A solução do sistema pode ser encontrada por meio da inversão da matriz dos coeficientes e da multiplicação da matriz inversa pela matriz dos termos independentes.

Veja:

$$ A_{x} =b $$
$$ A^{-1} * A_{x} = A^{-1}*b$$

Como:

$$A^{-1}*A = 1$$
$$x = A^{-1}*b$$

In [61]:
A = np.array([[1,2,3], [2,3,3], [1,2,0]])
B = np.array([1,-3,6])

In [62]:
A

array([[1, 2, 3],
       [2, 3, 3],
       [1, 2, 0]])

In [63]:
B

array([ 1, -3,  6])

Ax = b

x = A_inv * B

In [64]:
A_inv = np.linalg.inv(A)
A_inv

array([[-2.        ,  2.        , -1.        ],
       [ 1.        , -1.        ,  1.        ],
       [ 0.33333333, -0.        , -0.33333333]])

In [72]:
x = np.dot(A_inv, B)
print(f'A solução usando o método tradicional é:\n{x}')

A solução usando o método tradicional é:
[-14.          10.          -1.66666667]


## Resumo
- 1° Definimos a matriz A e o Vetor B
- 2° Calculamos inversa de A
- 3° Resolvendo o sistema de equação pela propriedade da matriz inversa

### Usando o Solve


In [76]:
# a função solve já calculado o resultado direto sem a necessidade de calcular a matriz inversa
x = np.linalg.solve(A,B)
print(f'A solução pelo solve é:\n`{x}')


A solução pelo solve é:
`[-14.          10.          -1.66666667]
