## Módulo Introdutório

Numpy é uma biblioteca mais rebuscada para resolver cálculos matemáticos e é a base do pandas

In [1]:
# importando numpy 
import numpy as np

In [3]:
lista = [1,2,3,4,5,6]

# Convertendo a lista em Array do Numpy
array = np.array(lista)

In [5]:
print(type(lista))
print(type(array))

<class 'list'>
<class 'numpy.ndarray'>


In [7]:
# Array de zeros
arr_zeros = np.zeros(10)
print(arr_zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [9]:
array[0]=9
print(array[0])

9


In [10]:
## matrizes
matriz_zeros = np.zeros((5,3))
print(matriz_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [12]:
# Notas de alunos 
lista_notas = [9.8,5.6,7.8,9.1,6.5]

notas = np.array(lista_notas)


In [19]:
print(f'Maximmo = {notas.max()}')
print(f'Mínimo = {notas.min()}')
print(f'Desvio Padrão = {round(notas.std(),2)}')
print(f'Media = {notas.mean()}')
print(f'Posição Menor = {notas.argmin()}')


Maximmo = 9.8
Mínimo = 5.6
Desvio Padrão = 1.56
Media = 7.76
Posição Menor = 1


## Máscara Booleana




In [24]:
is_covide_positive = np.array(['Yes', 'No', 'No','Yes', 'Yes','No'])
print(is_covide_positive)

['Yes' 'No' 'No' 'Yes' 'Yes' 'No']


In [26]:
# As vezes queremos filtrar dados por algum tipo de condição
# Ex.: Veficar casos positivos

mask = (is_covide_positive == 'Yes')
print(mask)


[ True False False  True  True False]


In [27]:
print(is_covide_positive[mask])

['Yes' 'Yes' 'Yes']


In [28]:
# podemos editar o array com o filtro
is_covide_positive[mask] = 'C19'
print(is_covide_positive)

['C19' 'No' 'No' 'C19' 'C19' 'No']


In [29]:
notas = np.array([4.9,6.5,3.2,6.7])
mask_notas = notas >=5

In [30]:
print(mask_notas)

[False  True False  True]


## Pandas Series

Além de ser indexada, podemos optar pelos índices em formato de chaves (dicionário)


In [31]:
import pandas as pd

c:\Users\Matheus\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (


In [32]:
lista = [12,23,34,45,56,67]

series_pandas  = pd.Series(lista)

In [34]:
print(series_pandas[0])

12


In [35]:
notas = {'Tiago': 8, 'Guilherme': 9.5, 'Juca': 6.2}

In [36]:
series_notas = pd.Series(notas)

In [37]:
print(series_notas['Tiago'])

8.0


In [39]:
print(series_notas.median())

8.0


In [40]:
print(series_notas.describe())

count    3.000000
mean     7.900000
std      1.652271
min      6.200000
25%      7.100000
50%      8.000000
75%      8.750000
max      9.500000
dtype: float64


## Pandas DataFrames

In [41]:
# Cria um dicionario com autores, preços e títulos

dict = {
    'Autores': ['Rick Riordan', 'J.R.R Tolkien', 'Rick Riordian', 'Machado de Assis' ],
    'Titulos': ['O Ladrão de Raios', 'A Sociedade do Anel', 'Mar de Monstros', 'Memórias Postumas de Brás Cubas'],
    'Preços':[41.2,35.7,39.5,40.5]
}

In [42]:
## Dataframe (dados em formato de tabelas)
df = pd.DataFrame(dict)

In [43]:
df.head()

Autores                          Titulos  Preços
0      Rick Riordan                O Ladrão de Raios    41.2
1     J.R.R Tolkien              A Sociedade do Anel    35.7
2     Rick Riordian                  Mar de Monstros    39.5
3  Machado de Assis  Memórias Postumas de Brás Cubas    40.5

In [45]:
df['Autores'][1]

'J.R.R Tolkien'

In [48]:
# media de preços
df['Preços'].mean()

39.225

In [50]:
mascara = (df['Autores'] == 'Rick Riordan')

In [51]:
df[mascara]

Autores            Titulos  Preços
0  Rick Riordan  O Ladrão de Raios    41.2

In [54]:
novo_dado = pd.DataFrame({'Autores': 'Rick Riordan', 'Titulos': 'A Maldição do Titã', 'Preços': [40.20]})

In [55]:
df = pd.concat([df, novo_dado], ignore_index=True)

In [56]:
df.head()

Autores                          Titulos  Preços
0      Rick Riordan                O Ladrão de Raios    41.2
1     J.R.R Tolkien              A Sociedade do Anel    35.7
2     Rick Riordian                  Mar de Monstros    39.5
3  Machado de Assis  Memórias Postumas de Brás Cubas    40.5
4      Rick Riordan               A Maldição do Titã    40.2

In [58]:
mask = df['Titulos'] == 'A Maldição do Titã'

In [60]:
df.loc[mask, 'Titulos'] = 'A Maldição Do Titã'
df.head()

Autores                          Titulos  Preços
0      Rick Riordan                O Ladrão de Raios    41.2
1     J.R.R Tolkien              A Sociedade do Anel    35.7
2     Rick Riordian                  Mar de Monstros    39.5
3  Machado de Assis  Memórias Postumas de Brás Cubas    40.5
4      Rick Riordan               A Maldição Do Titã    40.2