## Módulo Introdutório

Numpy é uma biblioteca mais rebuscada para resolver cálculos matemáticos e é a base do pandas

In [1]:
# importando numpy 
import numpy as np

In [3]:
lista = [1,2,3,4,5,6]

# Convertendo a lista em Array do Numpy
array = np.array(lista)

In [5]:
print(type(lista))
print(type(array))

<class 'list'>
<class 'numpy.ndarray'>


In [7]:
# Array de zeros
arr_zeros = np.zeros(10)
print(arr_zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [9]:
array[0]=9
print(array[0])

9


In [10]:
## matrizes
matriz_zeros = np.zeros((5,3))
print(matriz_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [12]:
# Notas de alunos 
lista_notas = [9.8,5.6,7.8,9.1,6.5]

notas = np.array(lista_notas)


In [19]:
print(f'Maximmo = {notas.max()}')
print(f'Mínimo = {notas.min()}')
print(f'Desvio Padrão = {round(notas.std(),2)}')
print(f'Media = {notas.mean()}')
print(f'Posição Menor = {notas.argmin()}')


Maximmo = 9.8
Mínimo = 5.6
Desvio Padrão = 1.56
Media = 7.76
Posição Menor = 1


## Máscara Booleana




In [24]:
is_covide_positive = np.array(['Yes', 'No', 'No','Yes', 'Yes','No'])
print(is_covide_positive)

['Yes' 'No' 'No' 'Yes' 'Yes' 'No']


In [26]:
# As vezes queremos filtrar dados por algum tipo de condição
# Ex.: Veficar casos positivos

mask = (is_covide_positive == 'Yes')
print(mask)


[ True False False  True  True False]


In [27]:
print(is_covide_positive[mask])

['Yes' 'Yes' 'Yes']


In [28]:
# podemos editar o array com o filtro
is_covide_positive[mask] = 'C19'
print(is_covide_positive)

['C19' 'No' 'No' 'C19' 'C19' 'No']


In [29]:
notas = np.array([4.9,6.5,3.2,6.7])
mask_notas = notas >=5

In [30]:
print(mask_notas)

[False  True False  True]
